import { Check, X } from 'lucide-react'
import { FadeIn } from '../ui/FadeIn'

const approved = ['artifact received · hash 0x84c1…7a03', 'gavel · rubric verified against commitment', 'exactly five headlines', 'brand name Somno appears', 'gavel · ruling APPROVED · 0.5 OKB released to seller']
const refunded = ['artifact received · hash 0xd113…4b8e', 'gavel · rubric verified against commitment', 'FAIL · exactly five headlines', 'FAIL · brand name Somno appears', 'gavel · ruling REFUNDED · 0.5 OKB returned to buyer']

/** Shows the two-run proof sequence as readable static terminal output. */
export function VerdictTerminals(): JSX.Element { const terminal = (items: string[], good: boolean, job: string) => <div className="overflow-hidden rounded-[8px] border border-[var(--border-default)] bg-[var(--bg-elevated)] shadow-[0_24px_48px_rgba(0,0,0,0.4)]"><div className="flex h-9 items-center gap-2 border-b border-[var(--border-subtle)] bg-[var(--bg-surface)] px-4"><span className="h-2.5 w-2.5 rounded-full bg-[var(--text-muted)]" /><span className="h-2.5 w-2.5 rounded-full bg-[var(--text-muted)] opacity-80" /><span className="h-2.5 w-2.5 rounded-full bg-[var(--text-muted)] opacity-60" /><span className="ml-2 font-mono text-xs text-[var(--text-muted)]">gavel · {job}</span></div><div className="p-6 font-mono text-[13px] leading-7"><div><span className="text-[var(--text-muted)]">$ </span><span className="text-[var(--text-primary)]">npx gavel-agent deliver --job {job.endsWith('01') ? '47' : '48'}</span></div>{items.map((item, index) => <div key={item} className={index === items.length - 1 || item.startsWith('FAIL') ? (good ? 't-approve' : 't-refund') : 'text-[var(--text-secondary)]'}><span className="mr-2 inline-flex align-middle">{index > 1 ? (item.startsWith('FAIL') || !good ? <X size={12} /> : <Check size={12} />) : null}</span>{item}</div>)}</div></div>
  return <section id="runs" className="border-t border-[var(--border-subtle)] bg-[var(--bg-secondary)] py-24 md:py-32"><div className="mx-auto max-w-6xl px-4 md:px-8"><FadeIn><h2 className="text-center font-display text-3xl tracking-tight text-[var(--text-primary)] md:text-5xl">Two runs. One judge.</h2><p className="mx-auto mt-4 max-w-[50ch] text-center font-body text-sm text-[var(--text-secondary)]">The same rubric grades both deliveries. Real work gets paid, junk gets refunded.</p></FadeIn><div className="mt-16 grid gap-6 lg:grid-cols-2"><FadeIn delay={0.3}>{terminal(approved, true, 'run 01')}</FadeIn><FadeIn delay={0.45}>{terminal(refunded, false, 'run 02')}</FadeIn></div></div></section> }
